# Generated by Django 5.0.1 on 2024-01-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narxi',
            name='narxi',
            field=models.IntegerField(blank=True, help_text='MASHINA_NARXI', null=True, verbose_name='narxi'),
        ),
    ]
