# Generated by Django 5.0.1 on 2024-01-06 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_rasm_rasm_alter_tortishi_tortsh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mashina',
            name='Tortishi',
        ),
    ]
