# Generated by Django 5.0.1 on 2024-01-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_mashina_tortishi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mashina',
            name='rasm',
            field=models.ManyToManyField(blank=True, null=True, to='news.rasm'),
        ),
    ]
