# Generated by Django 5.0.1 on 2024-01-06 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_mashina_rasm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mashina',
            name='Kuzov',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.kuzov'),
        ),
        migrations.AlterField(
            model_name='mashina',
            name='Manzil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.manzil'),
        ),
        migrations.AlterField(
            model_name='mashina',
            name='Narxi',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.narxi'),
        ),
        migrations.AlterField(
            model_name='mashina',
            name='Obyom',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.obyom'),
        ),
        migrations.AlterField(
            model_name='mashina',
            name='Peredacha',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.peredacha'),
        ),
        migrations.AlterField(
            model_name='mashina',
            name='Rang',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.rang'),
        ),
        migrations.AlterField(
            model_name='mashina',
            name='Turi',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.turi'),
        ),
        migrations.AlterField(
            model_name='mashina',
            name='Yana',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.yana'),
        ),
        migrations.AlterField(
            model_name='mashina',
            name='Yoqilgi',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.yoqilgi'),
        ),
        migrations.AlterField(
            model_name='mashina',
            name='yili',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.yili'),
        ),
    ]
