# Generated by Django 4.2.5 on 2024-01-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_mashina_kuzov_alter_mashina_manzil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mashina',
            name='rasm',
            field=models.ManyToManyField(to='news.rasm'),
        ),
    ]
