# Generated by Django 4.2.5 on 2024-01-08 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_mashina_rusumi_mashina_rusumi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mashina',
            name='Kuzov',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.kuzov'),
        ),
        migrations.AlterField(
            model_name='mashina',
            name='Manzil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.manzil'),
        ),
        migrations.AlterField(
            model_name='mashina',
            name='Narxi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.narxi'),
        ),
        migrations.AlterField(
            model_name='mashina',
            name='Obyom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.obyom'),
        ),
        migrations.AlterField(
            model_name='mashina',
            name='Peredacha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.peredacha'),
        ),
        migrations.AlterField(
            model_name='mashina',
            name='Rang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.rang'),
        ),
        migrations.AlterField(
            model_name='mashina',
            name='Turi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.turi'),
        ),
        migrations.AlterField(
            model_name='mashina',
            name='Yoqilgi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.yoqilgi'),
        ),
        migrations.AlterField(
            model_name='mashina',
            name='rusumi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.rusumi'),
        ),
        migrations.AlterField(
            model_name='mashina',
            name='yili',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.yili'),
        ),
    ]
